### ISSUE TITLE
Bug: Name Resets

### ISSUE THREAD

**Issue by DracoClaw** [12944qwerty/css-toggler#2]
When disabling and then enabling a snippet, the title resets.

**Comment by GriefMoDz** [comment]
As was previously discussed in the Powercord server, unfortunately both "I Won The Game" and I were unable to find a way to reproduce this bug. Due to this, we've decided that we'll be closing this issue. Please feel free to leave a comment on here again if you happen to continue experiencing this problem. Thank you.
